name: learn-github-actions #this is the learning file for GHA
run-name: ${{ github.actor }} is learning github learn-github-actions
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm install -g bats
    - run: bats -v

  check-python-version:
    needs: check-bats-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python: "3.13"
      - run: python -v

  slack-notification-failure:
    needs: 
      - check-bats-version
      - check-python-version
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Send Slack notification on failure
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "attachments": [
              {
                "color": "#FF0000",
                "pretext": "GitHub Actions Notification",
                "channel": "#gha-workflow"
                "title": ":x: GITHUB ACTIONS FLOW FAILURE :x:",
                "text": "\n\nAction Required: *DevOps* team to check on this failure.",
                "icon_emoji": ":exclamation:",
                "footer": "GitHub Actions",
                "ts": "'$(date +%s)'"
              }
            ]
          }' \
          ${{ secrets.GHA_SLACK_WEBHOOK }}

  slack-notification-success:
    needs: 
      - check-bats-version
      - check-python-version
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Send Slack notification on success
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "attachments": [
              {
                "color": "#36a64f",
                "pretext": "GitHub Actions Notification",
                "channel": "#gha-workflow"
                "title": ":white_check_mark: GITHUB ACTIONS FLOW SUCCESS :white_check_mark:",
                "text": "\n\nNo action required. Your GitHub Actions workflow has been completed successfully.",
                "icon_emoji": ":heavy_check_mark:",
                "footer": "GitHub Actions",
                "ts": "'$(date +%s)'"
              }
            ]
          }' \
          ${{ secrets.GHA_SLACK_WEBHOOK }}
