name: learn-github-actions #this is the learning file for GHA
run-name: ${{ github.actor }} is learning github learn-github-actions
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm install -g bats
    - run: bats -v

  check-python-version:
    needs: check-bats-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python: "3.13"
      - run: python -v

  notify-success:
    runs-on: ubuntu-latest
    needs: 
      - check-bats-version
      - check-python-version  # Only runs if the 'build' job succeeds
    if: success()   # Only runs if the 'build' job is successful
    steps:
      - name: Trigger success alert
        run: |
          "channel": "#gha-workflow",
          for channel in "${channels[@]}"; do
            response=$(curl -X POST -H 'Content-type: application/json' \
              --data '{
                "channel": "'$channel'",
                "pretext": "GitHub Actions Notification",
                "text": ":white_check_mark: *GHA DEPLOYMENT SUCCESSFUL* :rocket:",
                "attachments": [
                  {
                    "color": "good",
                    "footer": "GitHub Actions",
                    "ts": '$(date +%s)',
                    "fields": [
                      {
                        "title": "PULL REQUEST",
                        "value": "<${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}|#${{ github.event.pull_request.number }}>",
                        "short": true
                      },
                      {
                        "title": "GHA BUILD URL",
                        "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>",
                        "short": true
                      },
                      {
                        "title": "BRANCH",
                        "value": "<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.head_ref }}|${{ github.head_ref }}>",
                        "short": true
                      },
                      {
                        "title": "CHANGELOG",
                        "value": "- ${{ github.event.pull_request.title }} (@${{ github.actor }})",
                        "short": false
                      },
                    ]
                  }
                ]
              }' ${{ secrets.GHA_SLACK_WEBHOOK }})
            # Log the response for debugging
            echo "Response from Slack for channel $channel: $response"
            # Sleep to avoid rate limits (optional)
            sleep 1
          done
  notify-failure:
    runs-on: ubuntu-latest
    needs: 
      - check-bats-version
      - check-python-version  # Only runs if the 'build' job succeeds
    if: failure()   # Only runs if the 'build' job fails
    steps:
      - name: Trigger failure alert
        run: |
          "channel": "#gha-workflow",
          for channel in "${channels[@]}"; do
            response=$(curl -X POST -H 'Content-type: application/json' \
              --data '{
                "channel": "'$channel'",
                "text": ":x: *GHA DEPLOYMENT FAILED* :x:",
                "attachments": [
                  {
                    "color": "danger",
                    "footer": "GitHub Actions",
                    "ts": '$(date +%s)',
                    "fields": [
                      {
                        "title": "PULL REQUEST",
                        "value": "<${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}|#${{ github.event.pull_request.number }}>",
                        "short": true
                      },
                      {
                        "title": "GHA BUILD URL",
                        "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>",
                        "short": true
                      },
                      {
                        "title": "BRANCH",
                        "value": "<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.head_ref }}|${{ github.head_ref }}>",
                        "short": true
                      },
                      {
                        "title": "JOB",
                        "value": "${{ github.job }}",
                        "short": true
                      },
                      {
                        "title": "COMMIT",
                        "value": "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}> (@${{ github.actor }})",
                        "short": false
                      }
                    ]
                  }
                ]
              }' ${{ secrets.GHA_SLACK_WEBHOOK }})
            # Log the response for debugging
            echo "Response from Slack for channel $channel: $response"
            # Sleep to avoid rate limits (optional)
            sleep 1
          done